name: Auto-deploy example project

on:
  release:
    types: [published]

jobs:
  build-project:
    environment: Main
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
      # XXX libatomic is missing. looks like WLE github CI is outdated
      - run: apt-get install -y libatomic1
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      # XXX wonderland engine uses npm to run scripts instead of pnpm, but this isn't an issue... for now. it might be an issue in WLE 1.0.0
      - run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project example-project/example-project.wlp --credentials "$WLE_CREDENTIALS"
        env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'deploy/'

  deploy-project:
    if: startsWith(github.ref, 'refs/tags/releases/')
    needs: build-project
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
