name: Auto-deploy example project

on:
  release:
    types: [published]

jobs:
  build-project:
    environment: Main
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run copy-worker
      - run: npm run copy-manifold
      - run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project gypsum-example.wlp --credentials "$WLE_CREDENTIALS"
        env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'deploy/'

  deploy-project:
    if: startsWith(github.ref, 'refs/tags/releases/')
    needs: build-project
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
